# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4E_R0JAm9vgfXNmyEqClr8An5d0oaGc
"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
from IPython.display import HTML
from numba import jit, njit

t_0 = 100 #Количество кадров
delta_t = 1  #Шаг по времени

exp_min_T, exp_max_T = -2, 2 #Прикидка порядка Т
exp_min_P, exp_max_P = -2, 2 #Прикидка поряка P

epsilon = 1e-2 #Погрешность

T_end = 10.0   # Т в конце
L_0 = 0.0      # L в начале
m_0 = 0.0    # m в центре
P_end = 50.0   # P в конце

dr = 0.01
R_0 = 5.0   # Радиус в начале
max_steps = int(R_0 / dr)*100
M_0 = 80.0  # начальная M

@njit
def dM_dt(T_end, L_sum, R_0, t):
    return -2*t/125

@njit
def dT_dr(r, T, L, m, P, rho, t):
    return r*t

@njit
def dL_dr(r, T, L, m, P, rho, t):
    return 10*r*np.sin(t/10)

@njit
def dm_dr(r, T, L, m, P, rho, t):
    return (r**2)/(5*(t+2))

@njit
def dP_dr(r, T, L, m, P, rho, t):
    return -T

@njit
def ro(r, T, L, m, P, t):
    return 0.57 * P * T



def M_analytical(t):
    return M_0 -  (t**2)/125

def R_analytical(t):
    M = M_analytical(t)
    return (15 * (t + 2) * M) ** (1/3)

def T_analytical(r, t):
    R = R_analytical(t)
    return T_end + 0.5 * t * (r**2 - R**2)

def L_analytical(r, t):
    return 5.0 * np.sin(t/10) * r**2

def L_sum_analytical(t):
    R = R_analytical(t)
    return 5.0 * np.sin(t/10) * R**2

def m_analytical(r, t):
    return r**3 / (15 * (t + 2))

def P_analytical(r, t):
    R = R_analytical(t)
    term1 = P_end + T_end * (R - r)
    term2 = (t/6) * (R**3 - r**3)
    term3 = (t/2) * R**2 * (R - r)
    return term1 + term2 - term3

def rho_analytical(r, t):
    P_val = P_analytical(r, t)
    T_val = T_analytical(r, t)
    return 0.57 * P_val * T_val


def T0_analytical(t):
    R = R_analytical(t)
    return T_analytical(0.0, t)

@jit(nopython=True)
def solve_system_DE(current_time, epsilon, max_steps, dr,
             M_x,
             dT_dr, T_0,
             dL_dr, L_0,
             dm_dr, m_0,
             dP_dr, P_0,
             ro):

  r = np.arange(max_steps+1) * dr

  T = np.zeros((max_steps+1))
  T[0] = T_0

  L = np.zeros((max_steps+1))
  L[0] = L_0

  m = np.zeros((max_steps+1))
  m[0] = m_0

  P = np.zeros((max_steps+1))
  P[0] = P_0

  rho = np.zeros((max_steps+1))
  rho[0] = ro(0, T_0, L_0, m_0, P_0, current_time)

  stop = max_steps
  for i  in range(max_steps):

    if abs(m[i] - M_x) < epsilon*M_x:
      stop = i
      break

    k1_T = dT_dr(r[i], T[i], L[i], m[i], P[i], rho[i], current_time)
    k1_L = dL_dr(r[i], T[i], L[i], m[i], P[i], rho[i], current_time)
    k1_m = dm_dr(r[i], T[i], L[i], m[i], P[i], rho[i], current_time)
    k1_P = dP_dr(r[i], T[i], L[i], m[i], P[i], rho[i], current_time)


    T_2 = T[i] + dr * k1_T/2
    L_2 = L[i] + dr * k1_L/2
    m_2 = m[i] + dr * k1_m/2
    P_2 = P[i] + dr * k1_P/2
    rho_2 = ro(r[i]+dr/2, T_2, L_2, m_2, P_2, current_time)

    k2_T = dT_dr(r[i]+dr/2, T_2, L_2, m_2, P_2, rho_2, current_time)
    k2_L = dL_dr(r[i]+dr/2, T_2, L_2, m_2, P_2, rho_2, current_time)
    k2_m = dm_dr(r[i]+dr/2, T_2, L_2, m_2, P_2, rho_2, current_time)
    k2_P = dP_dr(r[i]+dr/2, T_2, L_2, m_2, P_2, rho_2, current_time)


    T_3 = T[i] + dr * k2_T/2
    L_3 = L[i] + dr * k2_L/2
    m_3 = m[i] + dr * k2_m/2
    P_3 = P[i] + dr * k2_P/2
    rho_3 = ro(r[i]+dr/2, T_3, L_3, m_3, P_3, current_time)

    k3_T = dT_dr(r[i]+dr/2, T_3, L_3, m_3, P_3, rho_3, current_time)
    k3_L = dL_dr(r[i]+dr/2, T_3, L_3, m_3, P_3, rho_3, current_time)
    k3_m = dm_dr(r[i]+dr/2, T_3, L_3, m_3, P_3, rho_3, current_time)
    k3_P = dP_dr(r[i]+dr/2, T_3, L_3, m_3, P_3, rho_3, current_time)


    T_4 = T[i] + dr * k3_T
    L_4 = L[i] + dr * k3_L
    m_4 = m[i] + dr * k3_m
    P_4 = P[i] + dr * k3_P
    rho_4 = ro(r[i]+dr, T_4, L_4, m_4, P_4, current_time)

    k4_T = dT_dr(r[i]+dr, T_4, L_4, m_4, P_4, rho_4, current_time)
    k4_L = dL_dr(r[i]+dr, T_4, L_4, m_4, P_4, rho_4, current_time)
    k4_m = dm_dr(r[i]+dr, T_4, L_4, m_4, P_4, rho_4, current_time)
    k4_P = dP_dr(r[i]+dr, T_4, L_4, m_4, P_4, rho_4, current_time)

    T[i+1] = T[i] + dr * (k1_T + 2*(k2_T + k3_T) + k4_T)/6

    L[i+1] = L[i] + dr * (k1_L + 2*(k2_L + k3_L) + k4_L)/6

    m[i+1] = m[i] + dr * (k1_m + 2*(k2_m + k3_m) + k4_m)/6

    P[i+1] = P[i] + dr * (k1_P + 2*(k2_P+k3_P)+k4_P)/6

    rho[i+1] = ro(r[i+1], T[i+1], L[i+1], m[i+1], P[i+1], current_time)

  return r, T, L, m, P, rho, stop


def find_the_origin(current_time, epsilon, max_steps, dr,
             exp_min_T, exp_max_T,
             exp_min_P, exp_max_P,
             M_x,
             dT_dr, T_end,
             dL_dr, L_0,
             dm_dr, m_0,
             dP_dr, P_end,
             ro):

  exp_T = (exp_min_T + exp_max_T)/2
  T_0 = 10**exp_T
  exp_P = (exp_min_P + exp_max_P)/2
  P_0 = 10**exp_P

  for _ in range(100):
    for _ in range(100):
        r, T, L, m, P, rho, stop = solve_system_DE(current_time, epsilon, max_steps, dr,
                M_x,
                dT_dr, T_0,
                dL_dr, L_0,
                dm_dr, m_0,
                dP_dr, P_0,
                ro)

        _, T_plus_dT, _, _, _, _, stop_T = solve_system_DE(current_time, epsilon, max_steps, dr,
                M_x,
                dT_dr, T_0*(1+1e-5),
                dL_dr, L_0,
                dm_dr, m_0,
                dP_dr, P_0,
                ro)

        _, _, _, _, P_plus_dP, _, stop_P = solve_system_DE(current_time, epsilon, max_steps, dr,
                M_x,
                dT_dr, T_0,
                dL_dr, L_0,
                dm_dr, m_0,
                dP_dr, P_0*(1+1e-5),
                ro)


        dF_dP_0 = (P_plus_dP[stop_P]-P[stop_P])/(1e-5*P_0)
        P_0 = P_0 - (P[stop] - P_end)/(dF_dP_0+1e-5)

        if abs(P[stop] - P_end) < epsilon*P_end and abs(T[stop] - T_end) < epsilon*T_end:
          break

    dF_dT_0 = (T_plus_dT[stop_T]-T[stop_T])/(1e-5*T_0)
    T_0 = T_0 - (T[stop] - T_end)/(dF_dT_0+1e-5)

  return r, T, L, m, P, rho, stop, T_0, P_0


def simulate(t_0, delta_t, epsilon, max_steps, dr,
             exp_min_T, exp_max_T,
             exp_min_P, exp_max_P,
             dM_dt, M_0,
             dT_dr, T_end,
             dL_dr, L_0,
             dm_dr, m_0,
             dP_dr, P_end,
             ro):

  frame_amount = int(t_0 // delta_t)
  t_points = np.arange(0, t_0, delta_t)

  r = np.arange(max_steps+1) * dr

  M_t = np.zeros(frame_amount+1)
  M_t[0] = M_0

  R_t, r_t, T_t, L_t, L_sum_t, m_t, P_t, rho_t = [], [], [], [], [], [], [], []


  for j in range(frame_amount):

    r, T, L, m, P, rho, stop, _, _ = find_the_origin(t_points[j], epsilon, max_steps, dr,
             exp_min_T, exp_max_T,
             exp_min_P, exp_max_P,
             M_t[j],
             dT_dr, T_end,
             dL_dr, L_0,
             dm_dr, m_0,
             dP_dr, P_end,
             ro)
    R_t.append(r[stop].copy())
    r_t.append(r[:stop+1].copy())
    T_t.append(T[:stop+1].copy())
    L_t.append(L[:stop+1].copy())
    L_sum_t.append(L[stop].copy())
    m_t.append(m[:stop+1].copy())
    P_t.append(P[:stop+1].copy())
    rho_t.append(rho[:stop+1].copy())


    M_t[j+1] = M_t[j] + delta_t * dM_dt(T_t[j][stop],
                                            L_t[j][stop],
                                            r[stop],
                                            t_points[j])

  return R_t, r_t, M_t, T_t, L_t, L_sum_t, m_t, P_t, rho_t



def make_animate_and_plots(t_0, delta_t, epsilon, max_steps, dr,
             exp_min_T, exp_max_T,
             exp_min_P, exp_max_P,
             dM_dt, M_0,
             dT_dr, T_end,
             dL_dr, L_0,
             dm_dr, m_0,
             dP_dr, P_end,
             ro):

  R_t, r_t, M_t, T_t, L_t, L_sum_t, m_t, P_t, rho_t = simulate(t_0, delta_t, epsilon, max_steps, dr,
             exp_min_T, exp_max_T,
             exp_min_P, exp_max_P,
             dM_dt, M_0,
             dT_dr, T_end,
             dL_dr, L_0,
             dm_dr, m_0,
             dP_dr, P_end,
             ro)


  frame_amount = int(t_0 // delta_t)
  t_points = np.arange(0, t_0, delta_t)



  R_max = max(R_t) # Считаем максимум для хороших границ
  M_max = max(M_t)
  T_max = max(np.max(profile) for profile in T_t)
  L_max = max(np.max(profile) for profile in L_t)
  L_sum_max = max(L_sum_t)
  m_max = max(np.max(profile) for profile in m_t)
  P_max = max(np.max(profile) for profile in P_t)
  rho_max = max(np.max(profile) for profile in rho_t)

  M_min = min(M_t)
  T_min = min(np.min(profile) for profile in T_t)
  L_min = min(np.min(profile) for profile in L_t)
  L_sum_min = min(L_sum_t)
  m_min = min(np.min(profile) for profile in m_t)
  P_min = min(np.min(profile) for profile in P_t)
  rho_min = min(np.min(profile) for profile in rho_t)

  fig, axes = plt.subplots(2, 4, figsize=(16, 10))

  plt.subplots_adjust(wspace=0.4, hspace=0.4)

  fig.tight_layout(pad=3.0, h_pad=2.0, w_pad=2.0)

  axes[0,0].set_xlim(-R_max*1.05, R_max*1.05)
  axes[0,0].set_ylim(-R_max*1.05, R_max*1.05)
  axes[0,0].set_aspect('equal')
  axes[0,0].grid(True, alpha=0.3) #alpha это чтобы сетка прозрачнее была и соответственно лучше смотрелась
  axes[0,0].set_title('Изменение радиуса звезды')

  axes[0,1].set_xlim(0, t_0)
  axes[0,1].set_ylim(M_min*1.05, M_max*1.05)
  axes[0,1].grid(True, alpha=0.3)
  axes[0,1].set_title('Изменение массы звезды')

  axes[0,2].set_xlim(0, R_max*1.05)
  axes[0,2].set_ylim(T_min*1.05, T_max*1.05)
  axes[0,2].grid(True, alpha=0.3)
  axes[0,2].set_title('Распределение температуры звезды')

  axes[0,3].set_xlim(0, R_max*1.05)
  axes[0,3].set_ylim(L_min*1.05, L_max*1.05)
  axes[0,3].grid(True, alpha=0.3)
  axes[0,3].set_title('Распределение светимости звезды')

  axes[1,0].set_xlim(0, t_0)
  axes[1,0].set_ylim(L_sum_min*1.05, L_sum_max*1.05)
  axes[1,0].grid(True, alpha=0.3)
  axes[1,0].set_title('Изменение полной светимости звезды')

  axes[1,1].set_xlim(0, R_max*1.05)
  axes[1,1].set_ylim(m_min*1.05, m_max*1.05)
  axes[1,1].grid(True, alpha=0.3)
  axes[1,1].set_title('Распределение массы звезды')

  axes[1,2].set_xlim(0, R_max*1.05)
  axes[1,2].set_ylim(P_min*1.05, P_max*1.05)
  axes[1,2].grid(True, alpha=0.3)
  axes[1,2].set_title('Распределение давления звезды')

  axes[1,3].set_xlim(0, R_max*1.05)
  axes[1,3].set_ylim(rho_min*1.05, rho_max*1.05)
  axes[1,3].grid(True, alpha=0.3)
  axes[1,3].set_title('Распределение плотности звезды')


  theta = np.linspace(0, 2*np.pi, 200) #Делаем нарезку единичной окружности в полярных координатах
  r_grid = np.linspace(0, 1, 100)
  th, R_grid = np.meshgrid(theta, r_grid)
  X = R_grid * np.cos(th) #Тут преобразуем в декартовые
  Y = R_grid * np.sin(th)

  time_text = axes[0,0].text(0.02, 0.95, '', transform=axes[0,0].transAxes, fontsize=12)
  M_text = axes[0,0].text(0.02, 0.85, '', transform=axes[0,0].transAxes, fontsize=12)
  R_text = axes[0,0].text(0.02, 0.75, '', transform=axes[0,0].transAxes, fontsize=12)
  an_R_text = axes[0,0].text(0.02, 0.65, '', transform=axes[0,0].transAxes, fontsize=12)

  contour_line, = axes[0,0].plot([], [], 'bo', linewidth=2.5, label='Контур') #Создаем контур фигуры

  M_ax, = axes[0,1].plot([], [], 'bo', linewidth=2.5, label='Масса')
  an_M_ax, = axes[0,1].plot([], [], 'r', linewidth=2.5, label='Масса')

  T_ax, = axes[0,2].plot([], [], 'bo', linewidth=2.5, label='Профиль температуры')
  an_T_ax, =  axes[0,2].plot([], [], 'r', linewidth=2.5, label='Профиль температуры')

  L_ax, = axes[0,3].plot([], [], 'bo', linewidth=2.5, label='Профиль светимости')
  an_L_ax, = axes[0,3].plot([], [], 'r', linewidth=2.5, label='Профиль светимости')

  L_sum_ax, = axes[1,0].plot([], [], 'bo', linewidth=2.5, label='Светимость')
  an_L_sum_ax, = axes[1,0].plot([], [], 'r', linewidth=2.5, label='Светимость')

  m_ax, = axes[1,1].plot([], [], 'bo', linewidth=2.5, label='Профиль массы')
  an_m_ax, = axes[1,1].plot([], [], 'r', linewidth=2.5, label='Профиль массы')

  P_ax, = axes[1,2].plot([], [], 'bo', linewidth=2.5, label='Профиль давления')
  an_P_ax, = axes[1,2].plot([], [], 'r', linewidth=2.5, label='Профиль давления')

  rho_ax, = axes[1,3].plot([], [], 'bo', linewidth=2.5, label='Профиль плотности')
  an_rho_ax, = axes[1,3].plot([], [], 'r', linewidth=2.5, label='Профиль плотности')


  T_min = min(np.min(T_slice) for T_slice in T_t)
  T_max = max(np.max(T_slice) for T_slice in T_t)
  norm = plt.Normalize(vmin=T_min, vmax=T_max) #Температура в цвет превращается
  cmap = plt.cm.plasma
  gradient_mesh = axes[0,0].pcolormesh(X, Y, np.zeros_like(R_grid), cmap='plasma', shading='gouraud')
  #Создаем градиент из нулей, shading отвечает за покраску клетки(gourand среднее между четыремя вершинами)
  #8
  sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
  sm.set_array([])
  cbar = plt.colorbar(sm, ax=axes[0,0], label='Температура') #Добавлем столбец с соответсвием цвета и величины градиента

  def init():
    contour_line.set_data([], [])
    M_ax.set_data([], [])
    an_M_ax.set_data([], [])

    T_ax.set_data([], [])
    an_T_ax.set_data([], [])

    L_ax.set_data([], [])
    an_L_ax.set_data([], [])

    L_sum_ax.set_data([], [])
    an_L_sum_ax.set_data([], [])

    m_ax.set_data([], [])
    an_m_ax.set_data([], [])

    P_ax.set_data([], [])
    an_P_ax.set_data([], [])

    rho_ax.set_data([], [])
    an_rho_ax.set_data([], [])


    time_text.set_text('')
    M_text.set_text('')
    R_text.set_text('')
    an_R_text.set_text('')


    return  contour_line, T_ax, M_ax, L_ax, L_sum_ax, m_ax, P_ax, rho_ax, gradient_mesh, time_text, M_text, R_text

  def animate(frame):
    nonlocal gradient_mesh

    current_time = t_points[frame]
    current_M = M_t[frame]
    current_R = R_t[frame]
    current_an_R = R_analytical(current_time)

    time_text.set_text(f't = {current_time:.2f} ')
    M_text.set_text(f'M = {current_M:.3f}')
    R_text.set_text(f'R = {current_R:.4f}')
    an_R_text.set_text(f'R = {current_an_R:.4f}')


    R_real = R_grid * R_t[frame]
    gradient = np.interp(R_real.ravel(), r_t[frame], T_t[frame]).reshape(R_real.shape)
    #9
    gradient_mesh.remove()#Удаляем старый градиент


    x_contour = R_t[frame] * np.cos(theta) #Находим координаты контура
    y_contour = R_t[frame] * np.sin(theta)
    contour_line.set_data(x_contour, y_contour)

    M_ax.set_data(t_points[:frame+1], M_t[:frame+1])
    an_M_ax.set_data(t_points[:frame+1], M_analytical(t_points[:frame+1]))

    T_ax.set_data(r_t[frame], T_t[frame])
    an_T_ax.set_data(R_real, T_analytical(R_real, current_time))

    L_ax.set_data(r_t[frame], L_t[frame])
    an_L_ax.set_data(R_real, L_analytical(R_real, current_time))

    L_sum_ax.set_data(t_points[:frame+1], L_sum_t[:frame+1])
    an_L_sum_ax.set_data(t_points[:frame+1], L_sum_analytical(t_points[:frame+1]))

    m_ax.set_data(r_t[frame], m_t[frame])
    an_m_ax.set_data(R_real, m_analytical(R_real, current_time))

    P_ax.set_data(r_t[frame], P_t[frame])
    an_P_ax.set_data(R_real, P_analytical(R_real, current_time))

    rho_ax.set_data(r_t[frame], rho_t[frame])
    an_rho_ax.set_data(R_real, rho_analytical(R_real, current_time))

    X_new = R_t[frame] * X #Точки, которые перекрашиваем
    Y_new = R_t[frame] * Y

    gradient_mesh = axes[0,0].pcolormesh(X_new, Y_new, gradient, cmap='plasma', shading='gouraud')#Делаем новый



    return contour_line, T_ax, M_ax, L_ax, L_sum_ax, m_ax, P_ax, rho_ax, gradient_mesh, time_text, M_text, R_text

  anim = FuncAnimation(fig, animate, frames=frame_amount,
                      init_func=init, interval=20, blit=False)#Заклинание создания анимации
  anim.save('star_evolution.gif',
            writer='pillow',  #Скачиваем анимацию ввиде GIF
            fps=20,
            dpi=150)


  from google.colab import files
  files.download('star_evolution.gif')
  plt.close()

  return anim


anim = make_animate_and_plots(t_0, delta_t, epsilon, max_steps, dr,
             exp_min_T, exp_max_T,
             exp_min_P, exp_max_P,
             dM_dt, M_0,
             dT_dr, T_end,
             dL_dr, L_0,
             dm_dr, m_0,
             dP_dr, P_end,
             ro)

HTML(anim.to_jshtml()) #Заклинание крутого показа анимации